repos:
-   repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
    - id: black
      args: [--line-length=88, --safe]
      language: python_venv
      language_version: python3
      files: ^(src/.*\.py|tests/.*\.py|setup\.py)
