repos:
-   repo: https://github.com/ambv/black
    rev: 18.6b1
    hooks:
    - id: black
      args: [--line-length=88, --safe]
      language: python_venv
      language_version: python3.6
      files: ^(src|tests)/.*\.py$
