version: '2'
services:
  webapp:
    build: tests/app
  firefox:
    image: selenium/standalone-firefox:latest
    depends_on:
      - "webapp"
  test:
    build:
      context: .
      dockerfile: tests/Dockerfile
    depends_on:
      - "webapp"
      - "firefox"
