version: 2
defaults: &defaults
  working_directory: /home/
  docker:
    - image: docker/compose:1.9.0
jobs:
  build:
    <<: *defaults
    steps:
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - checkout
      - run: docker-compose pull
      - run: docker-compose build
      - run:
          name: Run chromedriver tests
          command: |
            docker-compose \
              run \
              -e ARSENIC_SERVICE=Chromedriver \
              -e ARSENIC_BROWSER=Chrome?chromeOptions=%7B%22args%22%3A+%5B%22--headless%22%2C+%22--disable-gpu%22%2C+%22--no-sandbox%22%5D%7D \
              --rm \
              test-chromedriver
  setup:
    <<: *defaults
    steps:
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - checkout
      - run: docker-compose pull
      - run: docker-compose build
  chromedriver:
    <<: *defaults
    steps:
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - checkout
      - run:
          name: Run chromedriver tests
          command: |
            docker-compose \
              run \
              -e ARSENIC_SERVICE=Chromedriver \
              -e ARSENIC_BROWSER=Chrome?chromeOptions=%7B%22args%22%3A+%5B%22--headless%22%2C+%22--disable-gpu%22%2C+%22--no-sandbox%22%5D%7D \
              --rm \
              test-chromedriver
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - setup
      - chromedriver:
          requires:
            - setup
