version: 2
jobs:
  build:
    docker:
      - image: docker/compose:1.9.0
    working_directory: /home/
    steps:
      - setup_remote_docker
      - checkout
      - run: docker-compose build
      - run: docker-compose run -e WEB_APP_BASE_URL=http://webapp:5000 -e REMOTE_WEBDRIVERS=http://firefox:4444/wd/hub?browser=firefox -e DOCS_DIR=/code/docs/ -e SPHINXBUILD=/code/test-env/bin/sphinx-build --rm test
