version: 2
jobs:
  build:
    working_directory: /home/
    docker:
      - image: docker/compose:1.9.0
    steps:
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - checkout
      - run: docker-compose pull
      - run: docker-compose build
      - run:
          name: Run Geckodriver tests
          command: |
            docker-compose \
              run \
              -e ARSENIC_SERVICE=Geckodriver \
              -e ARSENIC_BROWSER=Firefox \
              -e ARSENIC_REMOTE=0 \
              -e DOCS_DIR=/code/docs/ \
              -e SPHINXBUILD=/code/test-env/bin/sphinx-build \
              --rm \
              test-geckodriver
      - run:
          name: Run PhantomJS tests
          command: |
            docker-compose \
              run \
              -e ARSENIC_SERVICE=PhantomJS \
              -e ARSENIC_BROWSER=PhantomJS \
              -e ARSENIC_REMOTE=0 \
              -e DOCS_DIR=/code/docs/ \
              -e SPHINXBUILD=/code/test-env/bin/sphinx-build \
              --rm \
              test-phantomjs
