version: 2
jobs:
  build:
    docker:
      - image: ojii/arsenic-test:latest
    working_directory: /home/ubuntu/arsenic
    steps:
      - checkout
      - run: python3.6 -mvenv /home/ubuntu/arsenic-env/
      - run: /home/ubuntu/arsenic-env/bin/pip install -U setuptools pip wheel
      - run: /home/ubuntu/arsenic-env/bin/pip install -e .
      - run: /home/ubuntu/arsenic-env/bin/pip install -r test-requirements.txt
      - run: find . -regex '.*__pycache__.*' -delete
      - run: xvfb-run /home/ubuntu/arsenic-env/bin/pytest --verbose --cov=src/arsenice --cov-report=html:reports/coverage/ --junitxml=reports/results/junit.xml --timeout=60
      - store_artifacts:
          path: reports/coverage/
          destination: reports
      - store_test_results:
          path: reports/results/
