version: 2
jobs:
  build:
    docker:
      - image: docker/compose:1.9.0
    working_directory: /home/
    steps:
      - setup_remote_docker
      - checkout
      - run: docker-compose build
      - run: docker-compose run --rm test
